### ISSUE TITLE
WorldFloods Dataset

### ISSUE THREAD

**Issue by zhaozhengChen** [blumenstiel/MESS#4]
Thank you for your excellent work!

I'm preparing the dataset following the provided instructions. I found that the number of images of WorldFloods differs from the reported one in the paper (53 vs. 160).

<img width="475" alt="截屏2024-01-08 下午8 58 42" src="https://github.com/blumenstiel/MESS/assets/35227544/096365d5-38d1-4b8d-b857-4479a1bbe38d">

**Comment by blumenstiel** [comment]
Thanks for checking the data in detail!

I had the following error when downloading the world floods with `gdown`:
```
AttributeError: 'NoneType' object has no attribute 'groups'
```
Did you experienced the same?

I downloaded the data manually from https://drive.google.com/drive/folders/1Bp1FXppikOpQrgth2lu5WjpYX7Lb2qOW.
After running the script I had 88 patches.

It looks like the google drive download does not return all tiles, leading to missing images.
I have to look into it tomorrow and come back to you.

**Comment by zhaozhengChen** [comment]
Thanks for your quick reply.

I tried to rerun the script and found that it can download the dataset automatically and get the correct number of images (160).

**Comment by blumenstiel** [comment]
Thanks for checking it again. I assume it was some error in the download from Google drive.

I'm going to add a check for the number of images so that others can be sure that all data is downloaded.

**Comment by zhaozhengChen** [comment]
Great! 
Thanks again!

**Comment by zhuyjan** [comment]
I downloaded the dataset from google drive manully and run the script, but I only got 88 images. How can I solve it?

**Comment by blumenstiel** [comment]
Maybe try it again? Not sure why it is failing some times.
