### ISSUE TITLE
how to use the indomain folder?

### ISSUE THREAD

**Issue by ChunmengLiu1** [blumenstiel/MESS#6]
Hi, thank you for your good job!

How can I use the indomain folder? I want to test the indomain results on Grounded-SAM.

**Comment by blumenstiel** [comment]
You can follow the description here: https://github.com/blumenstiel/MESS/tree/main/in_domain

Afterwards you can register the datasets with: `import in_domain.datasets`

**Comment by ChunmengLiu1** [comment]
Thank you so much! I solved it!
